import { Language, Dictionary, Monster } from './types';

export const dictionaries: Record<Language, Dictionary> = {
  "en": {
    title: "Monster Card Maker",
    preview: "Preview",
    form: "Monster Data",
    name: "Name",
    sizeType: "Size / Type",
    hp: "HP",
    defense: "Defense",
    speed: "Speed",
    damage: "Damage",
    body: "Body",
    mind: "Mind",
    magic: "Magic",
    spellName: "Spell name",
    spellDesc: "Description",
    hasAbilities: "Has abilities",
    hasSpecialAttacks: "Has special attacks",
    hasSpells: "Has spells",
    language: "Language",
    exportPng: "Export PNG",
    copyPng: "Copy PNG",
    reset: "Reset",
    stats: "Stats",
    abilityName: "Ability name",
    abilityDesc: "Ability description",
    specialAttackName: "Special attack name",
    specialAttackDesc: "Special attack description",
    addAbility: "Add ability",
    addSpecialAttack: "Add special attack",
    addSpell: "Add spell",
    abilities: "Abilities",
    specialAttacks: "Special Attacks",
    spells: "Spells",
    cardHeaders: {
      abilities: "Abilities",
      specialAttacks: "Special Attacks",
      spells: "Spells"
    }
  },
  "pt-BR": {
    title: "Criador de Cartas de Monstro",
    preview: "Pré-visualização",
    form: "Dados do Monstro",
    name: "Nome",
    sizeType: "Porte / Tipo",
    hp: "PV",
    defense: "Defesa",
    speed: "Velocidade",
    damage: "Dano",
    body: "Corpo",
    mind: "Mente",
    magic: "Magia",
    spellName: "Nome da magia",
    spellDesc: "Descrição",
    hasAbilities: "Tem habilidades",
    hasSpecialAttacks: "Tem ataques especiais",
    hasSpells: "Tem magias",
    language: "Idioma",
    exportPng: "Exportar PNG",
    copyPng: "Copiar PNG",
    reset: "Resetar",
    stats: "Atributos",
    abilityName: "Nome da habilidade",
    abilityDesc: "Descrição da habilidade",
    specialAttackName: "Nome do ataque especial",
    specialAttackDesc: "Descrição do ataque especial",
    addAbility: "Adicionar habilidade",
    addSpecialAttack: "Adicionar ataque especial",
    addSpell: "Adicionar magia",
    abilities: "Habilidades",
    specialAttacks: "Ataques Especiais",
    spells: "Magias",
    cardHeaders: {
      abilities: "Habilidades",
      specialAttacks: "Ataques Especiais",
      spells: "Magias"
    }
  }
} as const;

export const defaultMonster: Monster = {
  name: "",
  sizeType: "",
  hp: "",
  defense: "",
  speed: "",
  damage: "",
  body: "",
  mind: "",
  magic: "",
  abilities: [],
  specialAttacks: [],
  spells: [],
  hasAbilities: false,
  hasSpecialAttacks: false,
  hasSpells: false
};